---
title: "ST_pipeline"
output: html_document
---
Data: https://support.10xgenomics.com/spatial-gene-expression/datasets/1.0.0/V1_Breast_Cancer_Block_A_Section_1?
File contents help: https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/images


You MUST first unpack the gz files!!
```{r setup, include=FALSE}
#devtools::install_github("satijalab/seurat", ref = "spatial")
library(backports)
library(Seurat)
#library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)


library(Matrix)
library(rjson)
library(cowplot)
library(RColorBrewer)
library(grid)
library(readbitmap)
library(hdf5r)
library(data.table)

# Uninstall seurat
# install backports
# put backports on the R library
# devtools::install_github("satijalab/seurat", ref = "spatial") should work now

# must download file from https://www.xquartz.org/
#library(imager)

library(raster)
```

Load in spot position csv
```{r}
# Load in spot location CSV file(doesn't have headers)
image_location <- read.csv("C:/Users/malih/Desktop/Perkins_Lab_ST/Identifying (usable) image spots/data/spatial/tissue_positions_list.csv", header=FALSE)
names(image_location) <- c("barcode", "in_tissue", "array_row", "array_col", "pxl_col_in_fullres_yValue", "pxl_row_in_fullres_xValue")

image_location
```
 
trying to produce image
```{r}
setwd("C:/Users/malih/Desktop/Perkins_Lab_ST/Identifying (usable) image spots/data/")
file_name <- 'V1_Breast_Cancer_Block_A_Section_1_image.tif'

#creates a raster object from the tiff image file
#imported_raster <- raster(str_name)
wsi <- brick(file_name)

#check to see the image contains the correct amount of pixels
dim(wsi)
plotRGB(wsi)

e <- extent(13091, 13341, 4639, 4889)
cropped_img <- crop(wsi, e)
plotRGB(cropped_img)

# grabbing only the spots with tissue
image_location <- image_location %>%
  filter(in_tissue == 1)

#defining a function to get a cropped spot image given the x and y coordinates of the center of the spot
crop_spot <- function(img, x, y){
e <- extent(x - 136, #using 136 since it is ~half the average distance (273 pixels) between spot centers. We could consider using a different measure to more closely fit to the spot ratius.
              x + 136,
              y - 136,
              y + 136)
cropped_img <- crop(img, e)
return(cropped_img)
}

for (i in 1:length(image_location$in_tissue))
{
  cropped_img <- crop_spot(wsi, 
                           image_location$pxl_row_in_fullres_xValue[i], 
                           image_location$pxl_col_in_fullres_yValue[i])
  

#edit spot image 
  plotRGB(cropped_img)
}
```

```{r}
#for loop for function
rotate <- function(x) t(apply(x, 2, rev))
distort_spot <- function(img, times_to_rotate, colour_distortion_value){
  for (j in 1:times_to_rotate){#times_to_rotate is number 1 to 4
    for (i in 1:3){
      m <- matrix(getValues(img)[,i], nrow = nrow(img))
      m <- rotate(m)
      setValues(img, as.vector(m),layer = i)
    }
  }
  
    img <- raster::stretch(img, minq = colour_distortion_value, maxq = 1-colour_distortion_value)

  return(img)
}

plotRGB(cropped_img)
plotRGB(distort_spot(cropped_img,2,0.02))

```

```{r}
#one method for changing the contrast/brightness
#rotate <- function(x) t(apply(x, 2, rev))
for (i in 1)#length(image_location$in_tissue))
{
  #crop image to spot
  cropped_img <- crop_spot(wsi, 
                           image_location$pxl_row_in_fullres_xValue[i], 
                           image_location$pxl_col_in_fullres_yValue[i])
  #edit spot image
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1) <- as.vector(m)
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2) <- as.vector(m)
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3) <- as.vector(m)
  
  
  #edit spot's brightness
  stretch_image <- raster::stretch(cropped_img, minq = .02, maxq = .98)
  #stretch_image <- raster::stretch(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2, minq = .50, maxq = .65)
  #stretch_image <- raster::stretch(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3, minq = .50, maxq = .65)
  
  plotRGB(cropped_img)
  raster::plotRGB(stretch_image)
  
  raster::plotRGB(cropped_img,
        r = 1, g = 2, b = 3, scale= 600,stretch = "hist")
  raster::plotRGB(cropped_img,
        r = 1, g = 2, b = 3, scale= 500,stretch = "lin")
}

```

```{r}
#another method for adjusting the constrast
rotate <- function(x) t(apply(x, 2, rev))

for (i in 1:1)#length(image_location$in_tissue))
{
  #crop image to spot
  cropped_img <- crop_spot(wsi, 
                           image_location$pxl_row_in_fullres_xValue[i], 
                           image_location$pxl_col_in_fullres_yValue[i])
  #edit spot image
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1) <- as.vector(m)
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2) <- as.vector(m)
  m <- matrix(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3, nrow = 272)
  m <- rotate(m)
  values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3) <- as.vector(m)
  
  #plot spot image
  plotRGB(cropped_img)
  #wash_rgb_contrast_stretch <- raster::stretch(cropped_img, minq = .40, maxq = .60)
  raster::plotRGB(cropped_img)
}
```


```{r}
r <- raster(nrow=18, ncol=36)
m <- matrix(1:ncell(r), nrow=18)
#took our n matrix, transposed the matrix
values(r) <- as.vector(t(m))
extent(r) <- extent(0, 360, -90, 90)
rr <- rotate(r)
```

Messing around to learn about indexing from raster images and learned the average pixel distance between spot centers
```{r}
#selecting specific rows from the (red) raster image
cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1[50:100,50:100] <- vector(mode="integer", length=length(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1[50:100,50:100]))

# when looking at the 3 different image chanels in the raster object, image 1 is red, 2 is green, and 3 is blue
values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1) <- vector(mode="integer", length=length(values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.1))) 

values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2) <- vector(mode="integer", length=length(values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.2))) 

values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3) <- vector(mode="integer", length=length(values(cropped_img$V1_Breast_Cancer_Block_A_Section_1_image.3))) 

#writeRaster(cropped_img, filename='data/testingRaster', format='GTiff', bandorder='BIL', overwrite=TRUE)


#checking the pixel distance between spots
differences <- c()
for (xIndex in seq(3, 127, by=2))
{
  for (yIndex in seq(3, 127, by=2))
  {
    differenceLeft <- image_location$pxl_row_in_fullres_xValue[image_location$array_row == xIndex & image_location$array_col == yIndex] - image_location$pxl_row_in_fullres_xValue[image_location$array_row == xIndex & image_location$array_col == yIndex - 2]
    differenceDown <- image_location$pxl_col_in_fullres_yValue[image_location$array_row == xIndex & image_location$array_col == yIndex] - image_location$pxl_col_in_fullres_yValue[image_location$array_row == xIndex - 1 & image_location$array_col == yIndex - 1]
    differences <- c(differences, differenceLeft)
    append(differences, differenceDown)
  }
}
mean(differences)
hist(differences)
```

